### ISSUE TITLE
Project settings

### ISSUE THREAD

**Issue by fmaussion** [ehultee/chakra#1]
I don't have access to your project settings, but I recommend to set to only allow "squash merging" for a cleaner history on pull-requests - for the PRs to come ;-)

**Comment by ehultee** [comment]
It was previously set to enable merge, squash, and rebase.  I've deselected merge and rebase now.

I'm happy to give you access to the settings if possible.  Based on the GitHub help pages I can't see how to adjust permissions like that in a user-owned repository, but if you know how to do it please advise.
