### ISSUE TITLE
Document apply_parameterization

### ISSUE THREAD

**Issue by ehultee** [ehultee/chakra#6]
Attribute "apply_parameterization" within chakra.CalvingModel seems to be doing the work of activating calving, but it is not described in the docstring.  Only appears 5 times in chakra.py; as far as I can see each one is just setting the attribute--not using it.  We should improve documentation of apply_parameterization so it is clear how to manipulate it.

**Comment by fmaussion** [comment]
Yes, good point. I didn't want to spend too much time on it before we agree it's useful.

Passing a callable function is the only way to give external code the ability to change something *within* the numerical timestep without changing the code in the class itself. It is useful only if you don't need to change anything in the numerics. themselves.

With this you can remove or shift around mass, have access to all internal model states, etc. I'm not sure this is going to work for you though, and you might simply change the code in the class directly.

**Comment by fmaussion** [comment]
>  Only appears 5 times in chakra.py;

yes, because it can apply an arbitrary function. In the tests and the notebook I defined this super simple one:

https://github.com/ehultee/chakra/blob/5d28cec279f31a0a8520915fd62f8f6ba64b87dc/test_chakra.py#L290-L322

Which basically simply removes mass where we want it to.

**Comment by ehultee** [comment]
Yes I saw that - I just didn't see the function _called_ anywhere in the code or in the notebook.  But maybe you wrote it so that defining self.apply_parameterization both sets *and calls* some arbitrary function at each timestep?

**Comment by fmaussion** [comment]
> defining self.apply_parameterization both sets and calls some arbitrary function at each timestep?

Yes, the call happens here:

https://github.com/ehultee/chakra/blob/5d28cec279f31a0a8520915fd62f8f6ba64b87dc/chakra.py#L324-L327

Before the time steps ends.

**Comment by fmaussion** [comment]
yaaaa, apply_parameterization won't work ;)
